/*File generated automatically. Do not edit*/
int CheckMove(othello * jg, int code) ;
int GenerateMove(othello * jg) ;
int GetPlayerMove(void) ;
void InitGame( othello *jg) ;
int LoadGame(othello *jg) ;
int PrintGameBoard(othello *jg) ;
int SaveGame(othello *jg, int savenum) ;
void SwapValues( char *a, char *b) ;
int WinGame(othello * jg) ;
void call_error_(int errorn) ;
int campo_de_jogo_(othello *jg) ;
int change_line_do_(othello * jg, int i, int j) ;
int change_line_do_le_(othello * jg, int i, int j) ;
int change_line_do_ri_(othello * jg, int i, int j) ;
int change_line_le_(othello * jg, int i, int j) ;
int change_line_ri_(othello * jg, int i, int j) ;
int change_line_up_(othello * jg, int i, int j) ;
int change_line_up_le_(othello * jg, int i, int j) ;
int change_line_up_ri_(othello * jg, int i, int j) ;
int change_piece_(othello * jg, int i, int j) ;
int change_piece_1_(othello * jg, int i, int j) ;
int check_do_(othello * jg, int ii, int jj) ;
int check_do_le_(othello * jg, int ii, int jj) ;
int check_do_ri_(othello * jg, int ii, int jj) ;
int check_le_(othello * jg, int ii, int jj) ;
int check_ri_(othello * jg, int ii, int jj) ;
int check_up_(othello * jg, int ii, int jj) ;
int check_up_le_(othello * jg, int ii, int jj) ;
int check_up_ri_(othello * jg, int ii, int jj) ;
void clear_for_next_move_(othello * jg) ;
int compare_string_(char *first, char *second, int n1, int n2) ;
void create_masck_( othello *jg , othello *jgm) ;
void disp_controls_(void) ;
void disp_error_(int errorn) ;
void display_first_space_(int kk, int n) ;
void display_last_space_(int kk, int n) ;
void display_screen_1_(int color) ;
void display_screen_str_(char * tit, int n, int n1) ;
int get_pos_m_(int pos, int npos) ;
int get_saves_in_dir_(int * saves) ;
int isanumber_(char ch) ;
char *keypress(unsigned char echo, int n) ;
void limparshell_(void) ;
int load_bord_(othello *jg, int savenum) ;
void make_base_(void) ;
void make_game_ovre_(void) ;
void make_header_(void) ;
int make_move_(othello * jg, int move) ;
int make_score_(othello * jg) ;
int num_saves_in_dir_(void) ;
int pag0_(othello *jg) ;
int pag1_(othello *jg) ;
int pag2_(othello *dummy) ;
int pag3_(othello *dummy) ;
int pag4_(othello *dummy) ;
int pag5_(othello *jg) ;
int pag6_(othello *jg) ;
int possible_moves_(othello * jg) ;
void print_board_border_(void) ;
void print_board_cell_(char cell, int cellc) ;
void print_c_(char * s, int n) ;
void print_load_resolt_(othello * jg) ;
void print_menu_(int pos,int m, int npl) ;
int print_menu_load_(int pos,int m, int * saves) ;
void print_save_resolt_(othello * jg) ;
void textcolor1(int attr, int fg, int bg) ;
void textcolor2(int fg) ;
void update_vez_(othello * jg) ;
